### ISSUE TITLE
Support 0MQ

### ISSUE THREAD

**Issue by iancooper** [iancooper/Paramore#10]
As well as amqp and RestMS it would be worth supporting 0MQ to 'get the set'

**Comment by MrHypnos** [comment]
I'm up for this one.

**Comment by iancooper** [comment]
All yours :-)

**Comment by iancooper** [comment]
This still looks tricky with our model, parked for now

**Comment by iancooper** [comment]
The key issue is that we have a broker topology, not a brokerless topology. We don't support point-to-point and actually rely on the HA features of a broker. Fixing this would require the support of either point-to-point in Brighter, or adding a Broker, which kind of defeats the purpose. As we can go to Helios for point-to-point this may be easier than reaching for 0MQ
