### ISSUE TITLE
Stopping pipeline processing without logging an error

### ISSUE THREAD

**Issue by george-ayris** [iancooper/Paramore#119]
It was suggested the best approach would be a custom exception type. Just to double check that this is  the way to go and it should be implemented in a similar manner to DeferMessageAction apart from it should acknowledge the message and log either at info or debug?

**Comment by ianbattersby** [comment]
I don't think we should use exceptions for flow-control unless absolutely necessary, I find it inherently smelly!

I thought we had a poison message approach for this? Why do we get an error? Is it the CancellationToken being invoked during an I/O operation? As otherwise we should be able to control it no?

**Comment by george-ayris** [comment]
I'm happy to go down a different route - that's what @iancooper was suggesting. 

At the minute to stop processing of a message (e.g. if a version check fails) we just have to throw an exception that gets logged as an error. Is there a better way of doing this at the minute?

**Comment by holytshirt** [comment]
@george-ayris it depends on what you want to do, if the check fails; do you want to throw away the message? then just `return command;` or do you want to requeue the message? then  `throw new DeferMessageAction;` neither of those will log an error

**Comment by george-ayris** [comment]
I would like to throw it away and stop the rest of the pipeline processing. So by not doing `return base.Handle(command);` and instead doing `return comand;` then that will achieve that?

**Comment by holytshirt** [comment]
Yes, that is the correct way in a Russian doll pipeline

-----Original Message-----
