### ISSUE TITLE
When a message is discarded, the error log should dump out the content of the message

### ISSUE THREAD

**Issue by benjamin-hodgson** [iancooper/Paramore#121]
At the moment, the error says:

```
MessagePump: Have tried 30 times to handle this message c92f7655-ed00-4eae-8a50-5562fbda2a25 (original message id 2e62348b-1c72-4de3-aeda-0d39aa4bb6b3) from Files.MyHuddle.UserRemovedFromGroup.Event on thread # 48, dropping message
```

When we then go to manually replay a message, there is no information in the log about which aggregate the message was from. It would be much easier to debug issues (by replaying messages, etc) if the error contained a JSON dump of the message.

**Comment by holytshirt** [comment]
@benjamin-hodgson check the merge and close if you are happy

**Comment by benjamin-hodgson** [comment]
:+1:
