### ISSUE TITLE
Support termination with extreme predjudice

### ISSUE THREAD

**Issue by iancooper** [iancooper/Paramore#143]
Our termination model puts a quit message into the queue so that the message pump will read the quit instruction once it has processed the existing message, and before reading from the broker's queue. This causes orderly shutdown of all of our queues, with no partial completion.

For some scenarios this is a problem: the main one seems to be where the time taken to process a message is long (due to the length of the operation, or waiting for other resources to be free). When  serviceactivator is being used in a windows service this means that we fail to shut down in the agreed time frame. so Windows will report an error. However, we will eventually shut down once we are signalled to shut down, so this behaviour can be both furstrating (time taken to shut down) and unexpected (we shut at an unexpected future point).

So for people who have long running handlers we want to provide the option to immediately terminate. Our assumption is that you will only use the option if you are idempotent and happy that work may be partially complete when terminated. As we will not ack, the abandoned jobs will be loaded when we resume.

We don't want to pass a cancellation token to the handlers to effect this. Our concern here is bleeding the TPL into the handler code, and creating accidental complexity for those that do not require this. In addition, simply signalling cancellation might not resolve the issue if the use case is not a loop or similiar that allows regular checks that we should continue to progress.

The simplest approach here is probably that where we are configured to support termination with predjudice to run the dispatcher inside an appdomain and unload that appdomain when we are instructed to stop. See http://www.superstarcoders.com/blogs/posts/executing-code-in-a-separate-application-domain-using-c-sharp.aspx

Note that this is not perfect, but its the only way for us to say - yes, really abort everything here.

http://stackoverflow.com/questions/4432141/how-to-properly-unload-an-appdomain-using-c

As I say, this should be opt in, so we could just simply document using the above Isolated approach, and create our own version with a facade or Dispatcher and equivalent code (with suitable attribution to this article) to Isolated<T> to wrap it.

Thoughts welcome.

**Comment by ianbattersby** [comment]
Ouch, but yeah I'm not bursting with alternatives! Perhaps as the codebase grows it's a sync hairs bleeding TPL into implementation into handlers won't feel so wrong.

We should though pass cancellation tokens into internal operations such as requeue wait mechanisms and Polly?

**Comment by iancooper** [comment]
I think this one will get picked up by the async work where we are adding cancellation tokens. Once we get service activator in a position to support an async pipeline then it should be possible to use an async pipeline for a long-running operation and then use the cancellation token mechanism to signal termination. Going to work in Huddle on using the former to fix our instance of the latter.
