### ISSUE TITLE
HelloWorld demo uses an older builder syntax

### ISSUE THREAD

**Issue by iancooper** [iancooper/Paramore#145]
We now have DefaultPolicy not NoPolicy. Documentation needs updating.

**Comment by rudygt** [comment]
If you need help, let me know, just tell me how the html is generated, I made a quick search and can't locate the files used to create the html.

**Comment by iancooper** [comment]
@rudygt We use GitHub pages. So you need to switch to the gh-pages branch. It is s static site there. Feel free to mark the issue us 'grabbed by community' if you want to fix.

**Comment by rudygt** [comment]
@iancooper Thanks!, can you please add the label? I'm happy to help, I think I can't add labels right?
