### ISSUE TITLE
Improved logging messages for easier debugging

### ISSUE THREAD

**Issue by okouam** [iancooper/Paramore#164]
In some places when reviewing the logs we can see the command/event type along with its ID, while in others only the ID is provided. This is a minor issue but would make debugging much easier if the pattern of showing the command/event type along with its ID was used consistently throughout whenever logging the identity of a message.

**Comment by ianbattersby** [comment]
:+1: .. PR?

**Comment by iancooper** [comment]
I'm looking at logging tests as part of the async work. So I can review, but it would be great if you could highight which ones are an issue, or even better issue a PR :-)
