### ISSUE TITLE
Support RMQ transient (non-durable) exchanges 

### ISSUE THREAD

**Issue by ianbattersby** [iancooper/Paramore#171]
Reported by @Wooderz, if you configure Brighter to use a transient (non-durable) exchange it gives the following error:

```
The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=406, text=\"PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'exchange.wooderz' in vhost '/': received 'false' but current is 'true'\", classId=40, methodId=10, cause=",
```

Presumably we don't have durability as a config option then so the `ExchangeDeclare` call is forcing it to durable, and when the exchange isn't, it errors. We should provide a configuration attribute or similar.

Edit: https://github.com/iancooper/Paramore/blob/3d3c604d9ad9aeb1a44accbff00fc5399c5a7871/Brighter/paramore.brighter.commandprocessor.messaginggateway.rmq/MessageGatewayHelper.cs#L37

**Comment by holytshirt** [comment]
@ianbattersby there is a config setting https://github.com/iancooper/Paramore/blob/master/Brighter/paramore.brighter.commandprocessor.messaginggateway.rmq/MessagingGatewayConfiguration/RMQMessagingGatewayConfigurationSection.cs#L216-L225

**Comment by ianbattersby** [comment]
I know, it's ignored ;-)

**Comment by holytshirt** [comment]
It can't be ignored, must be working as our exchange is durable. We have to add ```durable="true"``` as the default is false.

Or am I missing something here?

**Comment by ianbattersby** [comment]
Apologies, I'm thinking about exchange type.

I need sleep :sleeps:
