### ISSUE TITLE
SqlMessageStore duplicate-key exceptions fail under Polly policy

### ISSUE THREAD

**Issue by ianbattersby** [iancooper/Paramore#178]
We noticed some time ago that we were getting Polly failing on inserting messages into the message-store when RMQ wasn't available; what we observed was;

1. Message is queued with `Post()`
2. Message is added to the SQL message store
3. Attempt is made to connect to RMQ and fails - Polly kicks in - hazzah!
4. On retry message is added to the SQL message store
5. SqlException is triggered as already exists
6. Polly kicks in and starts a new retry without following `try/catch` statements

Do the catching of the `SqlException`'s which then checked to make sure if it was merely a duplicate-key and ignore it, simply didn't work under Polly. One option could be to tell Polly to ignore SqlException but this would exclude a raft of other possible scenarios. More so using exceptions for logic-flow - especially with SQL Server proper - seems wrong. Another option _could_ be to try and write a Policy that filters the `SqlException`'s but this policy would be unique to SqlMessageStore and only there for SqlServerCe.

My thoughts are that anyone in their right mind wouldn't be using SqlServerCe for production and at some point we need to get rid, but for the purposes of a quick fix having a SQL Server version that does it properly and a SqlServerCe version that does it's best but isn't atomic, is perhaps workable.

PR incoming for consideration.

**Comment by ianbattersby** [comment]
The other downside of this commit is it even more diverges the code-path for two supported providers when only one provider is included in the tests. Ideally we need a way to test SQL proper during CI test runs, or with manual tests.

**Comment by ianbattersby** [comment]
cc @iancooper

**Comment by iancooper** [comment]
yeah, we should talk about this one over our lunch. SQLCE has always been there because of difficulty running this out-of-the-box. But now SQL Server is free (https://blogs.technet.microsoft.com/dataplatforminsider/2016/03/31/microsoft-sql-server-developer-edition-is-now-free/) maybe we just ship the DDL and tell you to build it. Not sure.

**Comment by iancooper** [comment]
No problem btw with us merging Command and Message Store. It's only an artefact of don't try to re-use until v3 or it hurts. If it hurts let's make it one.
