### ISSUE TITLE
Remove legacy NuGet package - ExceptionPolicy

### ISSUE THREAD

**Issue by ianbattersby** [iancooper/Paramore#183]
Couple of our guys fell foul of pulling this in without realising it had since been merged into `commandprocessor`, suggest this nuget is removed (made private/hidden) asap!

https://www.nuget.org/packages/Paramore.Brighter.CommandProcessor.ExceptionPolicy/

**Comment by iancooper** [comment]
Yeah, I'm not sure if I can delete from NuGet. It's a pain, but it is the same issue that npm recently had - deleting means people who have downloaded cannot use. I might be able to request deletion as confusing.

**Comment by iancooper** [comment]
Ah ok. I need to unlist https://docs.nuget.org/create/deleting-packages 

Hang on

**Comment by iancooper** [comment]
OK should be unlisted. Can you close if you are happy?
