### ISSUE TITLE
Support multiple content types for messages

### ISSUE THREAD

**Issue by iancooper** [iancooper/Paramore#189]
We support application/json via plain/text today. We should really support XML, JSON, and Binary as folks may want to use different text based wire-formats, or binary (particularly protobuf). RabbitMQ client for .NET supports these three, so we should look at enabling clients to provide any one of those message bodies

https://dotnetcodr.com/2014/06/05/rabbitmq-in-net-data-serialisation/

Obviously we would set the type in the message mapper, and control serialization into the message there for .NET clients.

Interop is a goal here

**Comment by iancooper** [comment]
Taken by @smclewin

**Comment by smclewin** [comment]
Pull request issued for https://github.com/smclewin/Paramore/tree/binary-messages.  I missed where to attach the pull request to issue #189.

**Comment by iancooper** [comment]
We've merged in the code that allows a message body to be binary. We haven't added special default for existing text/plain as we can support existing clients with a constructor and property that allow it as a default. Examples left out for now, we'll create something soon, based off the PR. We do need to work with @smclewin to move the tools to Paramore.Contrib which is the appropriate home for them.
