### ISSUE TITLE
Support async versions of Send and Publish

### ISSUE THREAD

**Issue by iancooper** [iancooper/Paramore#3]

**Comment by iancooper** [comment]
Pondering upon this the issue that the asynchronous and synchronous pipelines are quite different. Consider that the in the Russian Doll model, if you await, then we have to consider what code will run as part of the completion (everything after the await inside the method body) and what code needs to run because we are now exiting the handler. This implies that the entire pipeline has to be async. It also means that we need to think about the default way that we call a successor now.

So I think the first thoughts here are wrong: this is a separate pipeline approach and we do need a SendAsync, PublishAsync, and PostAsync.

There is a some sharing - much of how we build a pipeline is similar, we just need different signatures, base objects in the async chain.

It would have been nice to support some async handlers in the chain, but I think the nature of async I/O and the russian doll model means that we can't effect this. So I think the whole pipeline has to be async.

The downside here, is that we won't find it easy to just call an existing pipeline using the *Async methods, you'll actually have to alter a handler to get support for async.

**Comment by Red-F** [comment]
Ian, I have read the above and after some (but definitely still insufficient) thinking created an implementation of SendAsync. The IAmACommandProcessor interface has been extended with:


```c#
        /// <summary>
        /// Awaitably sends the specified command.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="command">The command.</param>
        /// <returns>awaitable <see cref="Task"/>.</returns>
        Task SendAsync<T>(T command) where T : class, IRequest;
```

My current implementation builds a separate async pipeline, but does not  break any of the existing code, tests and examples.

There is actually not much 'my' code, just (copies of) existing code with modifications.

Added:
* AsyncHandlerFactory.cs
* AsyncPipelines.cs
* AsyncRequestHandler.cs
* AsyncRequestHandlerAttribute.cs
* AsyncRequestHandler.cs
* IAmAnAsyncHandlerFactory.cs
* IHandleRequestsAsync.cs
* a working HelloWorldAsync project

Modified:
* SpyCommandProcessor.cs (for tests)
* CommandProcessor.cs
* CommandProcessorBuilder.cs
* HandlerConfiguration.cs
* IAmACommandProcessor.cs
* IAmALifetime.cs
* Interpreter.cs
* LifetimeScope.cs
* PipelineBuilder.cs
* SubscriberRegistry.cs
* ReflectionExtensions.cs
* and the solution and relevant projects

Can you please create a branch named 'async' then I will issue a PR against it and we can review and discuss the approach I have taken so far. 

I have not yet created the Async equivalents of the eventsourcing, logging, monitoring and policy attributes but that is not a big deal. Also I'm still considering to support the use of 'regular' (non-async/await) handlers in the async pipeline. That shoiuld be doable. The other way around, using async handlers in a non-async pipeline, looks inadvisable.

Regards,
Fred Hoogduin

**Comment by iancooper** [comment]
I've created the async branch

**Comment by Red-F** [comment]
And the implementation of PublishAsync is waiting in PR #162

**Comment by iancooper** [comment]
We now have an implementation that supports the serviceactivator sending to an async pipeline if configured. For the moment building a genuine proactor model is out-of-scope.
