### ISSUE TITLE
HandlerFactory Release

### ISSUE THREAD

**Issue by critchie** [iancooper/Paramore#40]
I took notice that my handler factory Release was not being called for my command handler.  Digging into the Brighter code I realized that the handler is not added to the LifetimeScope unless the handler implements IDisposable.  Since a handler that doesn't implement IDisposable is never added to the LifetimeScope, Release will not be called for the handler.  I suppose if I have no real cleanup to do in my handler not calling Release would be OK and that it would eventually be disposed.

I thought I'd tell you because based on the documentation I fully expected Release to be called all the time.  So I don't know if this is really a code issue or a documentation issue.

**Comment by iancooper** [comment]
Hmmm, I guess we ought to think about giving the choice to the consumer on what to do. I think this dates from an earlier version where it was less clear who could make that call. We should probably fix and call Release on all handlers when the pipeline is dismantled. Anyone else?

**Comment by iancooper** [comment]
Fixed
