### ISSUE TITLE
Nuget Version Rollback?

### ISSUE THREAD

**Issue by critchie** [iancooper/Paramore#49]
As late as 02/27 1:46 PM EST NuGet pulled down version 3.0.94 with all the LibLog goodness and other changes.  When I pulled from NuGet at 02/27 6:36 PM EST I'm back at 2.0.1.0 with Common logging, etc.

Dazed and confused...

**Comment by holytshirt** [comment]
That it really odd, we have not rolled anything back. Just double checked and https://www.nuget.org/packages/Paramore.Brighter.CommandProcessor/ is at 3.0.94. That is very strange. 
Just a quick question which packages did you pull down?

**Comment by critchie** [comment]
Disregard and close.  Something on my end I guess.  The old version was in my packages folder.  Once it was deleted the right version appeared in the NuGet window.
