### ISSUE TITLE
Possible RmqMessageProducer Dispose Problem

### ISSUE THREAD

**Issue by critchie** [iancooper/Paramore#50]
I've created a microservice setup that uses TopShelf to host a OWIN self host service which starts a WebApp... pretty standard setup.  This microservice accepts a command, handles it, packages it up into an event which gets published to a RabbitMQ exchange.

My command processor setup seems trivial:

            RmqMessageProducer gateway = new RmqMessageProducer(logger);

                var commandProcessorBuilder = CommandProcessorBuilder
                    .With()
                    .Handlers(new HandlerConfiguration(BuildSubscriberRegistry(),
                        new AutofacCommandHandlerFactory(c.Resolve<IComponentContext>())))
                    //.NoPolicy()
                    .Policies(BuildPolicyRegistry())
                    .Logger(logger)
                    //.NoTaskQueues()
                    .TaskQueues(new MessagingConfiguration(couchbaseMessageStore,
                        gateway, BuildMessageMapperRegistry(c.Resolve<IComponentContext>())))
                    .RequestContextFactory(new InMemoryRequestContextFactory());

When I start the service and immediately stop it everything shuts down fine.

If I start it and actually send in a command the command is handled properly but when I shut down the service the service stops but the window does not close.  Visual Studio indicates that there is still a process running.  My investigation seems to point to the RmqMessageProducer not getting cleaned up.  If I turn off the policies and the task queues (bypassing the queue code) the service will shut down correctly.  Something is keeping the process running despite the Stop method being called on my service.

Any suggestions of what I can look into?

**Comment by holytshirt** [comment]
@critchie I'm going to try replicate this today, hopefully something simple. The rabbitmq client has been a pain to deal with.

**Comment by critchie** [comment]
I'll be glad to try any ideas you decide to try.

-Craig

**Comment by critchie** [comment]
How often do you release to NuGet?

**Comment by iancooper** [comment]
@critchie First, all of our Appveyor builds become NuGet packages, so you can download them. Just pick a build you want to use https://ci.appveyor.com/project/IanCooper/paramore/history and then click on the artefacts tab

Once you have the NuGet package locally, you can use them directly (see http://stackoverflow.com/questions/10240029/how-to-install-a-nuget-package-nupkg-file-locally)

It may be the easiest solution if you need bug fixes ahead of a push to the NuGet servers.

We then push to the NuGet servers when we think we have some stored value to share that we think everyone should take. It's very unlikely to be more than once every two weeks, and more likely to be once every month or two

**Comment by critchie** [comment]
Perfect thanks.
