### ISSUE TITLE
ConfigSection duplicated on NuGet Update

### ISSUE THREAD

**Issue by critchie** [iancooper/Paramore#52]
Low Priority...

In the ServiceActivator app.config.install.xdt

    <section name="serviceActivatorConnections" type="paramore.brighter.serviceactivator.ServiceActivatorConfiguration.ServiceActivatorConfigurationSection, paramore.brighter.serviceactivator" allowLocation="true" allowDefinition="Everywhere" xdt:Transform="Insert"/>

should be InsertIfMissing maybe?  Every time I upgrade I get the section even if it is already present.

**Comment by holytshirt** [comment]
Fixed in release v3.0.129
