### ISSUE TITLE
Can I use Brighter to run a pipeline of commands?

### ISSUE THREAD

**Issue by carlosagsmendes** [iancooper/Paramore#67]
Hi,

I've seen the [Not just layers! What can pipelines and events do for you? by Ian Cooper](http://www.ndcvideos.com/#/app/video/2441).

In the presentation Ian uses a [framework](https://github.com/iancooper/Styles/tree/master/DataFlow/Pipelines/Basic/BasicPipeline/Framework) to build a Pipes and Filters pipeline.

I was wondering if I can use Brighter to create pipelines of chained commands.

Since the `RequestHandler` has a `Successor` property I've been able to run chained commands like this:

```c#
var pump = new PumpCommandHandler(logger);
var filter1 = new Filter1CommandHandler(logger);
var filter2 = new Filter2CommandHandler(logger);  
var sink = new SinkCommandHandler(logger);
pump.Successor = filter1;
filter1.Successor = filter2;
filter2.Successor = sink;
```

I'm wondering if I'm supposed to use Brighter to do this... or if I should implement a Pipes and Filters pipeline instead.

Can you advise?

Thanks in advance

**Comment by iancooper** [comment]
Great question, and the answer is yes.

First, an apology. I am actively working on the documentation, it's not quite there, but it is coming along. 

The section you need is 'in progress' with only about half the first page written.

However, that page does explain some things you need to know: Derive from RequestHandler for you sink filter and for other filters in the pipeline. Use attributes derived from RequestAttribute to declare how the pipeline from the source to the sink handler is built. and then we will build the pipeline for you: http://iancooper.github.io/Paramore/BuildingAPipeline.html

You can do it manually, you just implement your handlers as you have done, mark the successors, and then register the first handler in your pipeline with us. You can either build in configuration code, or in your HandlerRequestFactory. Provided you derive from RequestHandler and call the base class Handle() method then your handler will simply call the next filter in the pipeline when it is done.

Take a look at the documentation. I'm hoping to have this section finished by c.o.p. next Tuesday.

**Comment by carlosagsmendes** [comment]
Many thanks for updating the documentation @iancooper!
