### ISSUE TITLE
Add support for delayed messaging via RabbitMQ using plugin and headers

### ISSUE THREAD

**Issue by iancooper** [iancooper/Paramore#72]
See http://www.rabbitmq.com/blog/2015/04/16/scheduling-messages-with-rabbitmq/
We need to add the headers to our message if someone intends to delay.
I suggest we add an optional parameter to Post with a default value of -1, that indicates the number of seconds to delay (-1 == no delay).

Other platforms i.e. RESTMS will need to figure out their own mechanism to support a delay

**Comment by ianbattersby** [comment]
Are we happy this is done or are we leaving open for the control bus stuff to adopt it?

**Comment by iancooper** [comment]
Let's call it done. We can open new issues for RestMS when I return to it.
